DROP TABLE NOMBRAMIENTOS;
DROP TABLE PARTICIPANTES;
DROP TABLE CUOTAS;
DROP TABLE LOGIN;
DROP TABLE CARGOS;
DROP TABLE TIPO_CUOTAS;
DROP TABLE ACTIVIDADES;
DROP TABLE TIPO_ACTIVIDADES;
DROP TABLE SOCIOS;


DROP SEQUENCE CARGOSID;
DROP SEQUENCE TIPOACTIVIDADID;
DROP SEQUENCE TIPOCUOTASID;
DROP SEQUENCE ACTICIDADESID;
DROP SEQUENCE SOCIOSID;

CREATE SEQUENCE CARGOSID;
CREATE SEQUENCE TIPOACTIVIDADID;
CREATE SEQUENCE TIPOCUOTASID;
CREATE SEQUENCE ACTIVIDADESID;
CREATE SEQUENCE SOCIOSID;

CREATE TABLE TIPO_ACTIVIDADES(
ID_TIPO NUMBER(6),
TIPO VARCHAR2(50),
CONSTRAINT TIP_PK PRIMARY KEY (ID_TIPO)
);

--tipo de cuotas
CREATE TABLE TIPO_CUOTAS(
ID_CUOTA NUMBER(6),
CANTIDAD NUMBER(3,2),
EDAD_LIMITE NUMBER(2),
NOMBRE VARCHAR2(50),
CONSTRAINT CUOT_PK PRIMARY KEY (ID_CUOTA)
);

CREATE TABLE CARGOS(
ID_CARGO NUMBER(6),
TIPO VARCHAR2(50),
CONSTRAINT CAR_PK PRIMARY KEY (ID_CARGO)
);

CREATE TABLE SOCIOS(
ID_SOCIO NUMBER(6),
NOMBRE VARCHAR2(50),
APELLIDOS VARCHAR2(100),
FECHA_NAC DATE,
DNI VARCHAR2(10),
TELEFONO NUMBER(9),
EMAIL VARCHAR2(100),
RESPONSABLE NUMBER(6),
PERFIL VARCHAR2(20) DEFAULT 'USUARIO',
FECHA_ALTA DATE,
FECHA_BAJA DATE,
CONSTRAINT SOC_PK PRIMARY KEY (ID_SOCIO),
CONSTRAINT SOC_SOC_FK FOREIGN KEY (RESPONSABLE) REFERENCES SOCIOS (ID_SOCIO) ON DELETE CASCADE
);

/*PROCEDIMIENTO PARA QUE DE DE BAJA AUTOMATICAMENTE AL SOCIO
SI TIENE LA CUOTA PAGADO*/

CREATE TABLE LOGIN(
USUARIO VARCHAR2(50),
ID_SOCIO NUMBER(6),
PASS VARCHAR2(100),
CONSTRAINT LOG_PK PRIMARY KEY (USUARIO, ID_SOCIO),
CONSTRAINT LOG_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO) ON DELETE CASCADE
);

CREATE TABLE ACTIVIDADES(
ID_ACTIVIDAD NUMBER(6),
FECHA DATE,
DESCRIPCION VARCHAR2(300),
DIFICULTAD VARCHAR2(10),
PRECIO NUMBER(4,2),
MOTIVO_CANCELACION VARCHAR2(100),
REALIZACION NUMBER(1), --boolean, 1 true y 0 false
ID_TIPO NUMBER(6),
ORGANIZADOR NUMBER(6),
CONSTRAINT ACT_PK PRIMARY KEY (ID_ACTIVIDAD),
CONSTRAINT ACT_TIP_FK FOREIGN KEY (ID_TIPO) REFERENCES TIPO_ACTIVIDADES(ID_TIPO) ON DELETE CASCADE,
CONSTRAINT ACT_SOC_FK FOREIGN KEY (ORGANIZADOR) REFERENCES SOCIOS (ID_SOCIO) ON DELETE CASCADE
);

CREATE TABLE NOMBRAMIENTOS(
ID_CARGO NUMBER(6),
ID_SOCIO NUMBER(6),
FECHA_INI DATE,
FECHA_FIN DATE,
CONSTRAINT NOM_PK PRIMARY KEY (ID_CARGO, ID_SOCIO, FECHA_INI),
CONSTRAINT NOM_CAR_FK FOREIGN KEY (ID_CARGO) REFERENCES CARGOS (ID_CARGO) ON DELETE CASCADE,
CONSTRAINT NOM_SOC_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS (ID_SOCIO) ON DELETE CASCADE
);

CREATE TABLE PARTICIPANTES(
ID_SOCIO NUMBER(6),
ID_ACTIVIDAD NUMBER(6),
CONSTRAINT PAR_PK PRIMARY KEY (ID_SOCIO, ID_ACTIVIDAD),
CONSTRAINT PAR_SOC_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS (ID_SOCIO) ON DELETE CASCADE,
CONSTRAINT PAR_ACT_FK FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES (ID_ACTIVIDAD) ON DELETE CASCADE
);

--Clase Cuotas
CREATE TABLE CUOTAS(
ID_SOCIO NUMBER(6),
ID_CUOTA NUMBER(6),
FECHA_PAGO DATE,
PAGADO NUMBER(1), --1 true, 0 false
CONSTRAINT REG_PK PRIMARY KEY (ID_SOCIO, ID_CUOTA, FECHA_PAGO),
CONSTRAINT REG_SOC_FK FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS (ID_SOCIO) ON DELETE CASCADE,
CONSTRAINT REG_CUO_FK FOREIGN KEY (ID_CUOTA) REFERENCES TIPO_CUOTAS (ID_CUOTA) ON DELETE CASCADE
);

--SOLO VA A EXISTIR LOS REGISTROS EN ESTA TABLA CUANDO EXISTA UNA FECHA DE PAGO
--SI NO EXISTE LA FECHA DE PAGO LOS DATOS SE OBTIENEN DE LA TABLA SOCIOS Y LA TABLA TIPO CUOTA

INSERT INTO TIPO_CUOTAS VALUES (TIPOCUOTASID.NEXTVAL,5,18,'INFANTIL');
INSERT INTO TIPO_CUOTAS VALUES (TIPOCUOTASID.NEXTVAL,15,29,'JUVENIL');
INSERT INTO TIPO_CUOTAS VALUES (TIPOCUOTASID.NEXTVAL,20,55,'ADULTO');


INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Saitama','Hagemanto','26/08/2008','82655125W','642624242','bultogirza@desoz.com',NULL,'ADMINISTRADOR','29/08/19',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Genos','Jenosu','28/06/1998','36568572K','618783240','zugnumufye@desoz.com',NULL,'ADMINISTRADOR','13/09/20',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Reena','Inverse','08/08/1988','88519217Z','634619896','vuknikorko@desoz.com',NULL,'ADMINISTRADOR','01/06/18',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Zelgadis','Graywords','03/03/2011','29379276L','684852047','vorkemirti@desoz.com',NULL,'ADMINISTRADOR','16/09/20',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Asuna','Yuuki','28/12/1981','29345776F','665544714','golmubakka@desoz.com',NULL,'ADMINISTRADOR','16/05/04',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Kirito','Kirigaya','12/05/2012','71493174C','681142645','bufyipokno@desoz.com',NULL,'ADMINISTRADOR','03/03/56',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Ichigo','Kurosaki','27/03/1973','51654438A','614065984','zotriropse@desoz.com',NULL,'ADMINISTRADOR','09/03/42',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Kisuke','Urahara','21/11/1990','48284167Z','786068813','naknujoste@desoz.com',NULL,'ADMINISTRADOR','04/03/67',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Son','Goku','05/09/2011','79466496R','788319038','vurkokerki@desoz.com',NULL,'ADMINISTRADOR','17/11/49',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Misa','Amane','11/02/2009','25137975X','758967461','voknohilti@desoz.com',NULL,'USUARIO','02/02/19',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Chihiro','Ogino','20/03/1983','46687169K','658780358','malmolakni@desoz.com',NULL,'USUARIO','09/07/96',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Kakashi','Hatake','18/02/2007','63881871S','679469338','tulmuyerte@desoz.com',NULL,'USUARIO','06/11/97',NULL);
INSERT INTO SOCIOS VALUES (SOCIOSID.NEXTVAL,'Naruto','Uzumaki','12/10/1977','71196171Q','682342002','faltolefya@desoz.com',NULL,'USUARIO','03/12/78',NULL);

INSERT INTO CARGOS VALUES (CARGOSID.NEXTVAL,'PRESIDENTE/A');
INSERT INTO CARGOS VALUES (CARGOSID.NEXTVAL,'VICEPRESIDENTE/A');
INSERT INTO CARGOS VALUES (CARGOSID.NEXTVAL,'SECRETARIO/A');
INSERT INTO CARGOS VALUES (CARGOSID.NEXTVAL,'TESORERO/A');
INSERT INTO CARGOS VALUES (CARGOSID.NEXTVAL,'VOCAL');

INSERT INTO NOMBRAMIENTOS VALUES(1,1,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(2,2,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(3,3,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(4,4,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(5,5,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(5,6,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(5,7,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(5,8,'11/02/2019',null);
INSERT INTO NOMBRAMIENTOS VALUES(5,9,'11/02/2019',null);

INSERT INTO TIPO_ACTIVIDADES VALUES(ACTIVIDADESID.NEXTVAL, 'SALIDA AL MONTE');
INSERT INTO TIPO_ACTIVIDADES VALUES(ACTIVIDADESID.NEXTVAL, 'ALBERGUE FIN DE SEMANA');
INSERT INTO TIPO_ACTIVIDADES VALUES(ACTIVIDADESID.NEXTVAL, 'REUNIÓN');
INSERT INTO TIPO_ACTIVIDADES VALUES(ACTIVIDADESID.NEXTVAL, 'COMIDA');
INSERT INTO TIPO_ACTIVIDADES VALUES(ACTIVIDADESID.NEXTVAL, 'OTROS');

INSERT INTO ACTIVIDADES VALUES (ACTIVIDADESID.NEXTVAL, '20/06/2019', 'Buen tiempo', 'BAJA', 20, null, null, 1, 1);
INSERT INTO ACTIVIDADES VALUES (ACTIVIDADESID.NEXTVAL, '10/06/2019', null, 'BAJA', 15, NULL, NULL, 3, 2);
INSERT INTO ACTIVIDADES VALUES (ACTIVIDADESID.NEXTVAL, '15/06/2019', 'Buen tiempo', 'ALTA', 20, null, null, 1, 1);
commit;

